- amqp/README.md
Hi,
`vhost` is missing from the specification. A virtual host (or `vhost`) is used to isolate an exchange or a queue:
https://www.rabbitmq.com/vhosts.html
> Add exchange.vhost and queue.vhost

- mqtt/README.md
- The field `qos` in the MQTT Bindings is described quite differently than in the specification:
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718099
> fix: description for MQTT QoS for Operation Binding Object

- README.md
- ibmmq/README.md
- Contribute IBM MQ AsyncAPI binding under Apache 2.0 license
- Created ibmmq bindings directory
- README updated to link to IBM MQ binding in ibmmq subdirectory
- NOTE: ibm-messaging fork created to facilitate this PR
`Resolves #48`
> feat: add IBM MQ binding

- kafka/README.md
- kafka/json_schemas/message.json
Refer to asyncapi/avro-schema-parser#67
Here is the related update due to the support of avro file in kafka key bindings
> feat(kafka): add AVRO type in message key binding

- CODEOWNERS
- solace/README.md
- solace/json_schemas/operation.json
- solace/json_schemas/server.json
The solace binding should have a topicSubscriptions field in the topic destination, just like we have for queues.
Also something was fixed in the schema. The schema had a property called 'exclusive' which should have been 'accessType.'
> feat: add topicSubscriptions to direct destinations.

- CODEOWNERS
- solace/README.md
Solace Binding Protocol has been included with release 2.3.0 of AsyncAPI,
with:
- https://github.com/asyncapi/spec/commit/88abbe0c86611f7e6a8f63cb37768ad45a51a761
- https://github.com/asyncapi/spec/pull/666
Thus, specification example should indicate at least this version.
While here, let's favor last released version 2.4.0, as suggested in https://github.com/asyncapi/bindings/pull/135#issuecomment-1135030435
Note:
Following https://github.com/asyncapi/bindings/pull/135#issuecomment-1134916216, this PR include a first commit to fix code owners orders.
---
Noticed by working on Solace Protocol support on https://bump.sh/asyncapi
> docs: adapt AsyncAPI version in Solace example

- solace/README.md
The README for the solace binding had some wording around which type of operation a binding applies to, e.g. a queue can only be used on a publish operation. We at Solace decided that this was too restrictive, there could be situations where you would need to add a queue binding on a subscribe operation. We decided it would be best to remove this wording to allow any binding to be used with either type of operation.
This does not affect the json schemas or parsers, the version number should not need to be changed.
> docs: remove wording about which type of operation a binding applies to

- CODEOWNERS
- README.md
- googlepubsub/README.md
- googlepubsub/json_schemas/channel.json
- googlepubsub/json_schemas/message.json
This commit contains two bindings, a `Channel Binding Object` and a `Message Binding Object` for Google Cloud Pub/Sub using the `googlepubsub` protocol name.
JSON Schema PR: https://github.com/asyncapi/spec-json-schemas/pull/253
Spec PR: https://github.com/asyncapi/spec/pull/836
> feat: add googlepubsub bindings

- kafka/README.md
- kafka/json_schemas/channel.json
- kafka/json_schemas/message.json
- kafka/json_schemas/operation.json
- kafka/json_schemas/server.json
As of today, there's no way using `0.2.0` version of Kafka bindings to provide information on whether a Schema Registry was/has to be used to provide/gather schema information for messages published on topics.
However, such information is required to help on two use-cases: 
1. Inform API providers to enable schema registry connection and pick the right vendor serdes,
2. Inform API consumers on the same things but also how to bypass if schema registry is unavailable
Use-cases and needed informations have been discussed with @nictownsend and @dalelane. This PR is aggregating validated propositions. The proposition is to add following attributes:
At the `server` level:
- `schemaRegistryUrl` - API URL for the Schema Registry used when producing Kafka messages
- …
> feat: add schema registry infos to Kafka binding

- CODEOWNERS
Adding @smoya and @char0n as code owners. Also adding @dalelane who seemed to be missing. Even though he's on the kafka binding but as a spec code owner I think he should also be code owner of all the bindings. What do you think?
https://github.com/asyncapi/spec/pull/846
https://github.com/asyncapi/spec-json-schemas/pull/271
> chore: add @smoya, @dalelane, and @char0n as code owners

- ibmmq/json_schemas/channel.json
When `destinationType=topic`, `queue` field MUST NOT be present and topic MAY be defined.
Refs #169
---
This change is a reaction to https://github.com/asyncapi/bindings/pull/169#issuecomment-1357795258 and https://github.com/asyncapi/bindings/pull/169#issuecomment-1359075613
> fix(ibmmq): make topic field optional

- CODEOWNERS
- jms/README.md
- jms/json_schemas/channel.json
- jms/json_schemas/message.json
- jms/json_schemas/server.json
Resolves https://github.com/asyncapi/spec/issues/919
This is a first draft of a set of JMS Binding Objects. There is a lot of variance between JMS Providers in terms of features and capabilities, however these bindings should work with all providers as they stay within the JMS API.
More features could of course be added in future if desirable!
> feat: first draft of JMS Binding Objects

- googlepubsub/README.md
Changes from v2 to v3:
* Bumped the `bindingVersion` values to `0.2.0`
* The `topic` property for the Channel Binding Object is no more and is now provided via the native `address` property of the Channel Object
* Protobuf support now uses the native support by providing the Protobuf definition as an inline string of the `schema` property within the `payload` property of the Message Object and the `schemaFormat` property within the `payload` property of the Message Object now has valid values for Protobuf 2 and 3
* The `type` property for the Message Binding Object is no more as AsyncAPI now natively support Protobuf and this value would duplicate the `schemaFormat` in the `payload` property of the Message Object
See also #182.
> feat: adapt googlepubsub bindings to v3

- sns/README.md
- sns/json_schemas/operation.json
Currently, filterPolicy configuration outlined in this file does not match what is outlined in the AWS documentation and API - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html. The `filterPolicy` should only contain the JSON policy, so no need for the `attributes` property; which in itself was confusing as the policy can apply to the message attributes or body.
Further to this, this definition file was missing the `filterPolicyScope` which is needed to determine whether the user wishes to filter on the message attributes or the body.
- ...
- ...
- ...
> docs: update FilterPolicy config to match AWS API

- kafka/README.md
This PR fixes a wrong git merge that happened in [kafka/README.md](kafka/README.md) file in https://github.com/asyncapi/bindings/pull/143#issuecomment-1798054517
https://github.com/asyncapi/bindings/pull/143#issuecomment-1798054517
cc @char0n
> fix: remove git HEAD marks left in Kafka binding README.md

- mqtt/README.md
- mqtt5/README.md
This PR updates the `next-major-spec` branch with latest `master` changes. Remember to merge this as regular commit NOT squash
> chore: update next-major-spec with master

- http/README.md
This PR adds the `statusCode` property to the message object.
The reason for adding it to the message object and not the operation object, is that it feels more natural, as the status code belong to each message being send.
```
...
channels:
HttpCustomersChannel:
address: /customers
messages:
HttpCustomersGetMessageResponse:
description: OK
payload:
$ref: '#/components/schemas/CustomerPaginated'
bindings:
http:
statusCode: 200
bindingVersion: '0.3.0'
HttpCustomersGetMessageResponse:
description: Server error, could not complete request
payload:
$ref: '#/components/schemas/SomeError'
bindings:
http:
statusCode: 500
bindingVersion: '0.3.0'
operations:
GetCustomers:
action: send
channel:
$ref: #/channels/HttpCustomersChannel
bindings:
http:
method: GET
bindingVersion: '0.3.0' …
```
> feat: add HTTP status code

- mqtt/README.md
- fix up broken links at mqtt binder
> fix: fix up links

- solace/README.md
- add new field:  timeToLive on a per operation bases.  
To enable to documentate what the a good valid related to the business logic of this event. For example if a temperature reading is publish every 30 sec. A ttl >30sec would make no sense.  
I choose  a per operation bases to align to https://github.com/asyncapi/bindings/blob/master/mqtt/README.md
- add new field: priority  on a per operation bases.  
To enable to documentate the importent ratings of events.
- add new field: dmqEligible on a per operation bases.  
To enable a message consumer to provide all necessary Information how the expected messages should look like.
> feat: solace add per operation fields

- kafka/README.md
- Updated additionalProperties flag as true
- Added 4 new properties to the topic configuration object
- Please see the related [issue](https://github.com/asyncapi/bindings/issues/231) for more details.
https://github.com/asyncapi/bindings/issues/231
> feat: updated kafka topic configuration object

- amqp/README.md
According to the JSON Schema files, you are only allowed to use exchange or queue depending on the `is`: https://github.com/asyncapi/spec-json-schemas/blob/287ed2846a764ac6ffce1d5034a9e3e47853a247/bindings/amqp/0.3.0/channel.json#L84
You cannot have both, which makes the example invalid.
> docs: fix incorrect example for AMQP

- sns/README.md
- sqs/README.md
The current AWS policy binding configuration doesn't match what is offered by AWS when configuring IAM policies. Condition and Resource are missing and Principal isn't fully fleshed out. This PR addresses this by extending the binding configuration for SNS and SQS.
Related spec JSON schema PR - https://github.com/asyncapi/spec-json-schemas/pull/553
N/A
> docs: update aws policy statement
